app = "ai-agent-earning"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  DAILY_EARNING_GOAL = "1.0"
  MAX_DAILY_TASKS = "10"
  RISK_TOLERANCE = "0.3"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  method = "GET"
  path = "/"
  timeout = "5s"
  grace_period = "5s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "data_volume"
  destination = "/app/data"